(()=>{const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const cars={
'jaguar-xj':{name:'Jaguar XJ',price:100000,img:'assets/jaguar-xj.jpg',cat:'Business'},
'jaguar-ftype':{name:'Jaguar F-Type',price:90000,img:'assets/jaguar-ftype.jpg',cat:'Sport'},
'range-rover':{name:'Range Rover',price:80000,img:'assets/range-rover.jpg',cat:'SUV'},
'velar':{name:'Range Rover Velar',price:70000,img:'assets/range-rover-velar.jpg',cat:'Premium SUV'}};
let user=null;const toast=t=>{const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2300)};
function authMode(mode){$('#loginPanel').hidden=mode!=='login';$('#registerPanel').hidden=mode!=='register';$('#authTitle').textContent=mode==='login'?'Войти в аккаунт':'Создать аккаунт';$('#authText').textContent=mode==='login'?'Управляйте бронированиями, избранными автомобилями и данными профиля.':'Регистрация занимает меньше минуты.'}
$('#showRegister').onclick=()=>authMode('register');$('#showLogin').onclick=()=>authMode('login');
$('#loginPanel').onsubmit=async e=>{e.preventDefault();const r=await QBPortal.login($('#loginIdentity').value,$('#loginPassword').value);$('#loginMsg').textContent=r.ok?'':r.error;if(r.ok){user=r.user;showAccount()}};
$('#registerPanel').onsubmit=async e=>{e.preventDefault();const name=$('#regName').value.trim(),phone=$('#regPhone').value.trim(),email=$('#regEmail').value.trim(),password=$('#regPassword').value,p2=$('#regPassword2').value;let err='';if(name.length<2)err='Введите имя';else if(phone.replace(/\D/g,'').length<10)err='Введите корректный номер';else if(password.length<8||!/[A-ZА-ЯЁ]/.test(password)||!/[a-zа-яё]/.test(password)||!/\d/.test(password))err='Пароль: 8+ символов, заглавная, строчная буква и цифра';else if(password!==p2)err='Пароли не совпадают';if(err){$('#registerMsg').textContent=err;return}const r=await QBPortal.register({name,phone,email,password});$('#registerMsg').textContent=r.ok?'':r.error;if(r.ok){user=r.user;showAccount()}};
function money(n){return new Intl.NumberFormat('ru-RU').format(n||0)+' ₸'}
function orderHTML(o){return `<div class="order-row"><div><b>${o.carName||o.service||'Заявка'}</b><span>${o.service||''}</span></div><div><b>${o.date||'Дата уточняется'}</b><span>${o.time||''}</span></div><div><b>${money(o.amount)}</b><span>${o.created||''}</span></div><span class="status-pill">${o.status||'Новая'}</span></div>`}
async function renderOrders(){const list=await QBPortal.orders();$('#countOrders').textContent=list.length;const empty='<div class="empty-state">Пока нет бронирований. Выберите автомобиль и отправьте первую заявку.</div>';$('#overviewOrders').innerHTML=list.length?list.slice(0,3).map(orderHTML).join(''):empty;$('#allOrders').innerHTML=list.length?list.map(orderHTML).join(''):empty}
function renderFavs(){const ids=[...new Set([...(JSON.parse(localStorage.getItem('qb_favorites_lux')||'[]')),...(JSON.parse(localStorage.getItem('qb_favorites')||'[]'))])].filter(id=>cars[id]);$('#countFavs').textContent=ids.length;$('#favoriteCars').innerHTML=ids.length?ids.map(id=>{const c=cars[id];return `<article class="car-card"><div class="car-photo"><img src="${c.img}" alt="${c.name}"></div><div class="car-body"><div class="car-cat">${c.cat}</div><h3>${c.name}</h3><div class="car-price">${money(c.price)} <small>/ сутки</small></div><a class="btn btn-gold wide" href="car.html?id=${id}">Открыть</a></div></article>`}).join(''):'<div class="empty-state">Добавляйте автомобили в избранное из автопарка.</div>'}
function fillProfile(){user=QBPortal.current()||user;if(!user)return;$('#portalName').textContent=user.name||'Клиент';$('#portalPhone').textContent=user.phone||user.email||'';$('#portalAvatar').textContent=(user.name||'Q').charAt(0).toUpperCase();$('#pName').value=user.name||'';$('#pPhone').value=user.phone||'';$('#pEmail').value=user.email||'';$('#pCity').value=user.profile?.city||'';$('#pNote').value=user.profile?.note||''}
function selectSection(name){$$('.portal-section').forEach(x=>x.classList.toggle('on',x.id==='sec-'+name));$$('[data-section]').forEach(x=>x.classList.toggle('on',x.dataset.section===name));history.replaceState(null,'','#'+name)}
$$('[data-section]').forEach(b=>b.onclick=()=>selectSection(b.dataset.section));$('#logoutBtn').onclick=async()=>{await QBPortal.logout();user=null;$('#accountShell').hidden=true;$('#authGate').hidden=false;authMode('login')};
$('#profileFormV14').onsubmit=async e=>{e.preventDefault();user=await QBPortal.updateProfile({name:$('#pName').value.trim(),email:$('#pEmail').value.trim(),profile:{city:$('#pCity').value.trim(),note:$('#pNote').value.trim()}});fillProfile();$('#profileMsg').textContent='Изменения сохранены';toast('Профиль обновлён')};
function bookingUI(){const car=['Автопрокат','Аренда с водителем'].includes($('#bService').value);$('#bCarWrap').style.display=car?'grid':'none';const taxi=['Такси','Трезвый водитель'].includes($('#bService').value);$('#fromWrap').style.display=taxi?'grid':'none';$('#toWrap').style.display=taxi?'grid':'none'}$('#bService').onchange=bookingUI;
$('#portalBooking').onsubmit=async e=>{e.preventDefault();const service=$('#bService').value,sel=$('#bCar'),opt=sel.selectedOptions[0],carId=sel.value;const o={id:Date.now(),service,name:user.name,phone:user.phone,date:$('#bDate').value,time:$('#bTime').value,carId,carName:carId?cars[carId]?.name:'',amount:carId?+(opt.dataset.price||0):0,from:$('#bFrom').value,to:$('#bTo').value,comment:$('#bComment').value,status:'Новая',created:new Date().toLocaleString('ru-RU')};if(['Автопрокат','Аренда с водителем'].includes(service)&&!carId){$('#bookingMsg').textContent='Выберите автомобиль';return}await QBPortal.saveOrder(o);$('#bookingMsg').textContent='Заявка отправлена. Менеджер свяжется для подтверждения.';toast('Заявка создана');renderOrders();setTimeout(()=>selectSection('bookings'),900)};
async function showAccount(){user=await QBPortal.me();if(!user)return;$('#authGate').hidden=true;$('#accountShell').hidden=false;fillProfile();renderFavs();await renderOrders();bookingUI();const p=new URLSearchParams(location.search),car=p.get('car'),service=p.get('service');if(car&&cars[car]){$('#bCar').value=car;$('#bService').value='Автопрокат';bookingUI();selectSection('newbooking')}else if(service){$('#bService').value=service==='taxi'?'Такси':service==='sober'?'Трезвый водитель':'Автопрокат';bookingUI();selectSection('newbooking')}else if(location.hash)selectSection(location.hash.slice(1))}
const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());$('#bDate').min=d.toISOString().slice(0,10);QBPortal.me().then(u=>{if(u){user=u;showAccount()}else{$('#authGate').hidden=false;$('#accountShell').hidden=true}});
})();
