const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>Number(n||0).toLocaleString('ru-RU')+' ₸';
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const seedCars=[
{id:'c1',name:'Jaguar XJ',price:100000,category:'Premium',year:2020,gear:'Автомат',seats:5,availability:'free',plate:'',description:'Премиальный седан для города и деловых поездок.',active:true,driver:true,image:'assets/jaguar-xj.jpg'},
{id:'c2',name:'Jaguar F-Type',price:90000,category:'Sport',year:2019,gear:'Автомат',seats:2,availability:'free',plate:'',description:'Спортивный автомобиль по предварительной заявке.',active:true,driver:false,image:'assets/jaguar-ftype.jpg'},
{id:'c3',name:'Range Rover',price:80000,category:'SUV',year:2020,gear:'Автомат',seats:5,availability:'busy',plate:'',description:'Премиальный SUV для города и межгорода.',active:true,driver:true,image:'assets/range-rover.jpg'},
{id:'c4',name:'Range Rover Velar',price:70000,category:'Premium SUV',year:2021,gear:'Автомат',seats:5,availability:'free',plate:'',description:'Комфортный премиальный кроссовер.',active:true,driver:false,image:'assets/range-rover-velar.jpg'}];
const seedServices=[
{id:'s1',name:'Автопрокат',price:'от 70 000 ₸',description:'Каталог автомобилей, бронь и подтверждение.',active:true},
{id:'s2',name:'Такси',price:'по расчёту',description:'Поездки по Атырау и межгороду.',active:true},
{id:'s3',name:'Трезвый водитель',price:'по расчёту',description:'Подача водителя по адресу клиента.',active:true},
{id:'s4',name:'Аренда с водителем',price:'по расчёту',description:'Автомобиль с персональным водителем.',active:true}];
const defaultSettings={company:'QAZAQ BOSS AUTORENT',whatsapp:'77752757063',phone:'+7 775 275 70 63',city:'Атырау',hours:'24/7 — онлайн-заявки',instagram:'',twoGis:'',supportEmail:'',faq:[{q:'Какие документы нужны для аренды?',a:'Удостоверение личности и водительское удостоверение. Точные условия подтверждает менеджер.'},{q:'Можно забронировать автомобиль с телефона?',a:'Да. Выберите автомобиль и даты, отправьте заявку и отслеживайте статус в личном кабинете.'},{q:'Как связаться с поддержкой?',a:'WhatsApp, телефон, Instagram и другие активные каналы доступны в разделе поддержки.'}],hero:'QAZAQ BOSS AUTORENT',subtitle:'Автопрокат • Такси • Трезвый водитель',success:'Менеджер подтвердит стоимость и доступность.',ordersEnabled:true};
let cars=JSON.parse(localStorage.getItem('qb_cars_v2')||'null')||seedCars;
let services=JSON.parse(localStorage.getItem('qb_services')||'null')||seedServices;
let settings={...defaultSettings,...JSON.parse(localStorage.getItem('qb_settings')||'{}')};
let carFilter='all';
const orders=()=>JSON.parse(localStorage.getItem('qb_orders')||'[]');
const setOrders=a=>localStorage.setItem('qb_orders',JSON.stringify(a));
function saveCars(){localStorage.setItem('qb_cars_v2',JSON.stringify(cars));renderAll()}
function saveServices(){localStorage.setItem('qb_services',JSON.stringify(services));renderAll()}
function statusClass(s){return {'Новая':'new','В работе':'work','Подтверждена':'ok','Завершена':'done','Отменена':'cancel'}[s]||'new'}
function availLabel(v){return v==='free'?'Свободен':v==='busy'?'Занят':'На обслуживании'}
function showTab(id){$$('.tabPage').forEach(x=>x.classList.toggle('hidden',x.id!==id));$$('.navItem').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));const btn=$(`.navItem[data-tab="${id}"]`);$('#pageTitle').textContent=btn?btn.innerText.replace(/\d+/g,'').trim():'Панель управления';document.body.classList.remove('navOpen');if(id==='calendar')renderCalendar()}
$$('.navItem').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
$('#menuBtn').onclick=()=>document.body.classList.toggle('navOpen');
function renderDashboard(){const a=orders(), today=new Date().toISOString().slice(0,10), todays=a.filter(x=>(x.date||'')===today);$('#kpiToday').textContent=todays.length;$('#kpiTodaySub').textContent=todays.filter(x=>x.status==='Новая').length+' новых';$('#kpiRevenue').textContent=money(a.filter(x=>x.status==='Завершена').reduce((s,x)=>s+Number(x.amount||0),0));$('#kpiCars').textContent=cars.length;$('#kpiCarsSub').textContent=cars.filter(x=>x.availability==='free'&&x.active).length+' доступно';const clients=new Set(a.map(x=>x.phone).filter(Boolean));$('#kpiClients').textContent=clients.size;$('#newBadge').textContent=a.filter(x=>x.status==='Новая').length;
const counts=['Новая','В работе','Подтверждена','Завершена','Отменена'].map(s=>[s,a.filter(x=>x.status===s).length]);$('#statusStats').innerHTML=counts.map(([s,n])=>`<div><span class="statusDot ${statusClass(s)}"></span><b>${s}</b><em>${n}</em><div class="miniProgress"><i style="width:${a.length?Math.round(n/a.length*100):0}%"></i></div></div>`).join('');
$('#recentRows').innerHTML=a.slice(0,6).map(o=>rowHtml(o,true)).join('')||emptyRow(6,'Пока заказов нет');renderChart()}
function renderChart(){const a=orders(), metric=$('#chartMetric').value;let days=[];for(let i=6;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);let iso=d.toISOString().slice(0,10);let val=metric==='orders'?a.filter(x=>x.date===iso).length:a.filter(x=>x.date===iso&&x.status==='Завершена').reduce((s,x)=>s+Number(x.amount||0),0);days.push({label:d.toLocaleDateString('ru-RU',{weekday:'short'}),val})}let max=Math.max(...days.map(x=>x.val),1);$('#chart').innerHTML=days.map(x=>`<div class="barCol"><div class="barValue">${metric==='orders'?x.val:(x.val/1000).toFixed(0)+'k'}</div><div class="barTrack"><i style="height:${Math.max(4,x.val/max*100)}%"></i></div><small>${x.label}</small></div>`).join('')}
$('#chartMetric').onchange=renderChart;
function rowHtml(o,compact=false){return `<tr><td><b>#${String(o.id).slice(-6)}</b>${compact?'':`<small>${esc(o.created||'')}</small>`}</td><td><b>${esc(o.name||'—')}</b><small>${esc(o.phone||'')}</small></td><td>${esc(o.service||'—')}<small>${esc(o.carName||'')}</small></td><td>${esc(o.date||'—')}<small>${esc(o.time||'')}</small></td><td><b>${money(o.amount||0)}</b></td><td><span class="statusPill ${statusClass(o.status)}">${esc(o.status||'Новая')}</span></td>${compact?'':`<td><button class="moreBtn" onclick="editOrder(${o.id})">Изм.</button></td>`}</tr>`}
function emptyRow(n,t){return `<tr><td colspan="${n}" class="emptyState">${t}</td></tr>`}
function renderOrders(){let a=orders(),q=$('#orderSearch').value.toLowerCase(),sf=$('#orderStatusFilter').value,sv=$('#orderServiceFilter').value;a=a.filter(o=>(!q||[o.name,o.phone,o.service,o.carName].join(' ').toLowerCase().includes(q))&&(!sf||o.status===sf)&&(!sv||o.service===sv));$('#orderRows').innerHTML=a.map(o=>rowHtml(o)).join('')||emptyRow(7,'Ничего не найдено')}
['orderSearch','orderStatusFilter','orderServiceFilter'].forEach(id=>$('#'+id).oninput=renderOrders);
function renderCars(){let q=$('#carSearch').value.toLowerCase();let a=cars.filter(c=>(!q||c.name.toLowerCase().includes(q))&&(carFilter==='all'||carFilter==='active'&&c.active||carFilter==='free'&&c.availability==='free'||carFilter==='busy'&&c.availability==='busy'));$('#carGrid').innerHTML=a.map(c=>`<article class="adminCar"><div class="carImg"><img src="${esc(c.image||'assets/car-front.jpg')}"><span class="avail ${c.availability}">${availLabel(c.availability)}</span><label class="publishSwitch"><input type="checkbox" ${c.active?'checked':''} onchange="toggleCar('${c.id}',this.checked)"><span></span></label></div><div class="carInfo"><div class="carTitle"><div><h3>${esc(c.name)}</h3><p>${esc(c.category||'')} • ${esc(c.year||'')} • ${esc(c.gear||'')}</p></div><b>${money(c.price)}<small>/ сутки</small></b></div><div class="carMeta"><span>◉ ${c.seats||5} мест</span><span>№ ${esc(c.plate||'не указан')}</span><span>${c.driver?'С водителем':'Без водителя'}</span></div><div class="carActions"><button onclick="editCar('${c.id}')">Редактировать</button><button onclick="duplicateCar('${c.id}')">Копия</button><button class="dangerTxt" onclick="deleteCar('${c.id}')">Удалить</button></div></div></article>`).join('')||'<div class="emptyCard">Автомобили не найдены</div>'}
$('#carSearch').oninput=renderCars;$$('[data-car-filter]').forEach(b=>b.onclick=()=>{$$('[data-car-filter]').forEach(x=>x.classList.remove('on'));b.classList.add('on');carFilter=b.dataset.carFilter;renderCars()});
function toggleCar(id,v){let c=cars.find(x=>x.id===id);if(c)c.active=v;saveCars()}function duplicateCar(id){let c=cars.find(x=>x.id===id);if(!c)return;cars.unshift({...c,id:'c'+Date.now(),name:c.name+' — копия'});saveCars()}function deleteCar(id){if(confirm('Удалить автомобиль из каталога?')){cars=cars.filter(x=>x.id!==id);saveCars()}}
function openCarModal(id){$('#carForm').reset();$('#carId').value='';$('#carPreview').src='assets/car-front.jpg';$('#carActive').checked=true;$('#carModalTitle').textContent='Добавить автомобиль';if(id){let c=cars.find(x=>x.id===id);if(!c)return;$('#carId').value=c.id;$('#carName').value=c.name;$('#carPrice').value=c.price;$('#carCategory').value=c.category||'Premium';$('#carYear').value=c.year||2024;$('#carGear').value=c.gear||'Автомат';$('#carSeats').value=c.seats||5;$('#carAvailability').value=c.availability||'free';$('#carPlate').value=c.plate||'';$('#carDescription').value=c.description||'';$('#carActive').checked=!!c.active;$('#carDriver').checked=!!c.driver;$('#carPreview').src=c.image||'assets/car-front.jpg';$('#carModalTitle').textContent='Редактировать автомобиль'}$('#carModal').classList.add('open')}
function editCar(id){openCarModal(id)}
$('#carImage').onchange=async e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>$('#carPreview').src=r.result;r.readAsDataURL(f);if(location.protocol==='http:'||location.protocol==='https:'){try{const fd=new FormData();fd.append('file',f);const res=await fetch('/api/upload',{method:'POST',body:fd});if(res.ok){const data=await res.json();$('#carPreview').src=data.url;toast?.('Фото загружено на сервер')}}catch(err){}}};
$('#carForm').onsubmit=e=>{e.preventDefault();let id=$('#carId').value||'c'+Date.now();let data={id,name:$('#carName').value.trim(),price:Number($('#carPrice').value),category:$('#carCategory').value,year:Number($('#carYear').value),gear:$('#carGear').value,seats:Number($('#carSeats').value),availability:$('#carAvailability').value,plate:$('#carPlate').value.trim(),description:$('#carDescription').value.trim(),active:$('#carActive').checked,driver:$('#carDriver').checked,image:$('#carPreview').src};let i=cars.findIndex(x=>x.id===id);if(i>=0)cars[i]=data;else cars.unshift(data);saveCars();closeModal('carModal')};
function renderServices(){$('#serviceGrid').innerHTML=services.map((s,i)=>`<article class="serviceEdit"><div class="serviceTop"><span>${String(i+1).padStart(2,'0')}</span><label class="switch"><input type="checkbox" ${s.active?'checked':''} onchange="services[${i}].active=this.checked;saveServices()"><i></i></label></div><input class="serviceName" value="${esc(s.name)}" onchange="services[${i}].name=this.value;saveServices()"><input value="${esc(s.price)}" onchange="services[${i}].price=this.value;saveServices()"><textarea rows="3" onchange="services[${i}].description=this.value;saveServices()">${esc(s.description)}</textarea><button class="dangerTxt" onclick="deleteService('${s.id}')">Удалить услугу</button></article>`).join('');let opts=services.filter(x=>x.active).map(s=>`<option>${esc(s.name)}</option>`).join('');$('#orderServiceFilter').innerHTML='<option value="">Все услуги</option>'+opts;$('#oService').innerHTML=opts}
function addService(){services.push({id:'s'+Date.now(),name:'Новая услуга',price:'по расчёту',description:'Описание услуги',active:true});saveServices()}function deleteService(id){if(confirm('Удалить услугу?')){services=services.filter(x=>x.id!==id);saveServices()}}
function renderClients(){let map={};orders().forEach(o=>{let k=o.phone||o.name;if(!k)return;if(!map[k])map[k]={name:o.name,phone:o.phone,count:0,last:o.date||'',amount:0};map[k].count++;map[k].amount+=Number(o.amount||0);if((o.date||'')>map[k].last)map[k].last=o.date});let a=Object.values(map).sort((x,y)=>y.count-x.count);$('#clientRows').innerHTML=a.map(c=>`<tr><td><b>${esc(c.name||'—')}</b></td><td>${esc(c.phone||'—')}</td><td>${c.count}</td><td>${esc(c.last||'—')}</td><td><b>${money(c.amount)}</b></td><td><span class="statusPill ok">Клиент</span></td></tr>`).join('')||emptyRow(6,'Клиентов пока нет')}
function renderCalendar(){let a=orders().filter(o=>['Подтверждена','В работе'].includes(o.status)&&o.date).sort((x,y)=>x.date.localeCompare(y.date));$('#calendarGrid').innerHTML=a.map(o=>`<article><div class="calDate"><b>${new Date(o.date+'T12:00:00').getDate()}</b><span>${new Date(o.date+'T12:00:00').toLocaleDateString('ru-RU',{month:'short'})}</span></div><div><b>${esc(o.carName||o.service)}</b><p>${esc(o.name)} • ${esc(o.time||'время не указано')}</p></div><span class="statusPill ${statusClass(o.status)}">${esc(o.status)}</span></article>`).join('')||'<div class="emptyCard">Подтверждённых бронирований пока нет</div>'}
function loadSettings(){if($('#setCompany'))$('#setCompany').value=settings.company||'';if($('#setWhatsapp'))$('#setWhatsapp').value=settings.whatsapp||'';if($('#setPhone'))$('#setPhone').value=settings.phone||'';if($('#setCity'))$('#setCity').value=settings.city||'';if($('#setHours'))$('#setHours').value=settings.hours||'';if($('#setInstagram'))$('#setInstagram').value=settings.instagram||'';if($('#setTwoGis'))$('#setTwoGis').value=settings.twoGis||'';if($('#setSupportEmail'))$('#setSupportEmail').value=settings.supportEmail||'';if($('#setHero'))$('#setHero').value=settings.hero||'';if($('#setSubtitle'))$('#setSubtitle').value=settings.subtitle||'';if($('#setSuccess'))$('#setSuccess').value=settings.success||'';if($('#setOrdersEnabled'))$('#setOrdersEnabled').checked=!!settings.ordersEnabled;renderFaqAdmin()}
function saveSettings(){settings={...settings,company:$('#setCompany').value,whatsapp:$('#setWhatsapp').value.replace(/\D/g,''),phone:$('#setPhone').value,city:$('#setCity').value,hours:$('#setHours').value,instagram:$('#setInstagram')?.value.trim()||'',twoGis:$('#setTwoGis')?.value.trim()||'',supportEmail:$('#setSupportEmail')?.value.trim()||'',hero:$('#setHero').value,subtitle:$('#setSubtitle').value,success:$('#setSuccess').value,ordersEnabled:$('#setOrdersEnabled').checked};localStorage.setItem('qb_settings',JSON.stringify(settings));alert('Настройки, контакты и FAQ сохранены.')}
function closeModal(id){$('#'+id).classList.remove('open')}
$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeModal(m.id)});
function openOrderModal(id){$('#orderFormAdmin').reset();$('#orderId').value='';$('#orderModalTitle').textContent='Новый заказ';$('#oCar').innerHTML='<option value="">Не выбран</option>'+cars.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');if(id){let o=orders().find(x=>x.id===id);if(!o)return;$('#orderId').value=o.id;$('#oName').value=o.name||'';$('#oPhone').value=o.phone||'';$('#oService').value=o.service||services[0]?.name;$('#oCar').value=o.carId||'';$('#oDate').value=o.date||'';$('#oTime').value=o.time||'';$('#oAmount').value=o.amount||0;$('#oStatus').value=o.status||'Новая';$('#oComment').value=o.comment||'';if($('#oDeposit'))$('#oDeposit').value=o.deposit||0;if($('#oDebt'))$('#oDebt').value=o.debt||0;if($('#oPromo'))$('#oPromo').value=o.promo||'';if($('#oDocsStatus'))$('#oDocsStatus').value=o.docsStatus||'Не проверены';if($('#oStaff'))$('#oStaff').value=o.staffId||'';if($('#oDriver'))$('#oDriver').value=o.driverId||'';if($('#oPaymentStatus'))$('#oPaymentStatus').value=o.paymentStatus||'Ожидается';if($('#oPaymentMethod'))$('#oPaymentMethod').value=o.paymentMethod||o.extra?.payment||'Kaspi / перевод';$('#orderModalTitle').textContent='Редактировать заказ'}$('#orderModal').classList.add('open')}
function editOrder(id){openOrderModal(id)}
$('#orderFormAdmin').onsubmit=e=>{e.preventDefault();let a=orders(),raw=$('#orderId').value,id=raw?Number(raw):Date.now(),car=cars.find(x=>x.id===$('#oCar').value);let data={id,name:$('#oName').value,phone:$('#oPhone').value,service:$('#oService').value,carId:car?.id||'',carName:car?.name||'',date:$('#oDate').value,time:$('#oTime').value,amount:Number($('#oAmount').value||0),status:$('#oStatus').value,driverId:$('#oDriver')?.value||'',driverName:(drivers.find(d=>d.id===$('#oDriver')?.value)||{}).name||'',paymentStatus:$('#oPaymentStatus')?.value||'Ожидается',paymentMethod:$('#oPaymentMethod')?.value||'Kaspi / перевод',deposit:Number($('#oDeposit')?.value||0),debt:Number($('#oDebt')?.value||0),promo:$('#oPromo')?.value||'',docsStatus:$('#oDocsStatus')?.value||'Не проверены',staffId:$('#oStaff')?.value||'',staffName:(staff.find(u=>u.id===$('#oStaff')?.value)||{}).name||'',comment:$('#oComment').value,created:new Date().toLocaleString('ru-RU')};let i=a.findIndex(x=>x.id===id);if(i>=0)data.created=a[i].created||data.created,i>=0?a[i]=data:0;else a.unshift(data);setOrders(a);closeModal('orderModal');renderAll()};
$('#seedBtn').onclick=()=>{let a=orders();if(a.length&& !confirm('Добавить ещё несколько демо-заказов?'))return;let d=new Date();const add=(off,name,phone,service,status,amount,car)=>{let x=new Date(d);x.setDate(x.getDate()+off);a.unshift({id:Date.now()+Math.random(),name,phone,service,status,amount,carName:car||'',date:x.toISOString().slice(0,10),time:'12:00',created:new Date().toLocaleString('ru-RU')})};add(0,'Арман','+7 701 111 22 33','Автопрокат','Новая',0,'Range Rover Velar');add(0,'Диас','+7 707 222 33 44','Такси','В работе',8500,'');add(1,'Марат','+7 775 333 44 55','Автопрокат','Подтверждена',80000,'Range Rover');add(-1,'Алия','+7 747 444 55 66','Трезвый водитель','Завершена',15000,'');setOrders(a);renderAll()};
$('#globalSearch').oninput=e=>{let q=e.target.value.trim();if(!q)return;showTab('orders');$('#orderSearch').value=q;renderOrders()};
function renderAll(){renderDashboard();renderOrders();renderCars();renderServices();renderClients();renderCalendar();loadSettings();if(typeof renderV3==='function')renderV3()}
// Initial render is executed after PRO V3 modules load.

// Keep desktop and mobile navigation synchronized
$$('.adminMobileNav .navItem').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
const _showTab=showTab;showTab=function(id){_showTab(id);$$('.adminMobileNav .navItem').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));};

// ===== PRO V3: drivers, payments, analytics, notifications, roles =====
let drivers=JSON.parse(localStorage.getItem('qb_drivers')||'null')||[
{id:'d1',name:'Нурлан',phone:'+7 701 555 20 20',type:'Трезвый водитель',status:'Свободен',rating:4.9,orders:38},
{id:'d2',name:'Арман',phone:'+7 707 441 11 10',type:'Такси / трансфер',status:'На заказе',rating:4.8,orders:52},
{id:'d3',name:'Данияр',phone:'+7 775 900 40 40',type:'Аренда с водителем',status:'Свободен',rating:5.0,orders:29}
];
let notices=JSON.parse(localStorage.getItem('qb_notices')||'null')||[
{id:'n1',name:'Бронь подтверждена',text:'Ваша бронь подтверждена. Автомобиль будет готов к указанному времени.',active:true},
{id:'n2',name:'Водитель назначен',text:'Водитель назначен и уже получил детали заказа.',active:true},
{id:'n3',name:'Напоминание об оплате',text:'Напоминаем об оплате заказа. Если уже оплатили — отправьте чек менеджеру.',active:true}
];
let staff=JSON.parse(localStorage.getItem('qb_staff')||'null')||[
{id:'u1',name:'Администратор',role:'Владелец',phone:'+7 775 275 70 63',access:'Полный доступ',active:true},
{id:'u2',name:'Диспетчер',role:'Менеджер',phone:'—',access:'Заказы, клиенты, водители',active:true}
];
function persistV3(){localStorage.setItem('qb_drivers',JSON.stringify(drivers));localStorage.setItem('qb_notices',JSON.stringify(notices));localStorage.setItem('qb_staff',JSON.stringify(staff));renderV3()}
function renderDrivers(){const g=$('#driverGrid');if(!g)return;g.innerHTML=drivers.map(d=>`<article class="driverCard"><div class="driverAvatar">${esc(d.name[0])}</div><div class="driverMain"><div class="driverHead"><div><h3>${esc(d.name)}</h3><p>${esc(d.type)}</p></div><span class="driverStatus ${d.status==='Свободен'?'free':'busy'}">${esc(d.status)}</span></div><div class="driverMeta"><span>${esc(d.phone)}</span><span>★ ${d.rating}</span><span>${d.orders} заказов</span></div><div class="carActions"><button onclick="toggleDriver('${d.id}')">${d.status==='Свободен'?'Назначить занятым':'Освободить'}</button><button class="dangerTxt" onclick="deleteDriver('${d.id}')">Удалить</button></div></div></article>`).join('')}
window.toggleDriver=id=>{const d=drivers.find(x=>x.id===id);if(d)d.status=d.status==='Свободен'?'На заказе':'Свободен';persistV3()};window.deleteDriver=id=>{if(confirm('Удалить водителя?')){drivers=drivers.filter(x=>x.id!==id);persistV3()}};
$('#addDriverBtn')?.addEventListener('click',()=>{const name=prompt('Имя водителя');if(!name)return;const phone=prompt('Телефон','+7 ');drivers.unshift({id:'d'+Date.now(),name,phone:phone||'',type:'Водитель',status:'Свободен',rating:5,orders:0});persistV3()});
function renderPayments(){const a=orders();const paid=a.filter(o=>o.paymentStatus==='Оплачено'||o.status==='Завершена').reduce((s,o)=>s+Number(o.amount||0),0);const pending=a.filter(o=>!['Завершена','Отменена'].includes(o.status)).reduce((s,o)=>s+Number(o.amount||0),0);if($('#payPaid'))$('#payPaid').textContent=money(paid);if($('#payPending'))$('#payPending').textContent=money(pending);if($('#paymentRows'))$('#paymentRows').innerHTML=a.map(o=>`<tr><td><b>#${String(o.id).slice(-6)}</b></td><td><b>${esc(o.name||'—')}</b><small>${esc(o.phone||'')}</small></td><td><b>${money(o.amount||0)}</b></td><td>${esc(o.paymentMethod||o.extra?.payment||'Не указан')}</td><td><span class="statusPill ${o.paymentStatus==='Оплачено'||o.status==='Завершена'?'ok':'work'}">${esc(o.paymentStatus||(o.status==='Завершена'?'Оплачено':'Ожидается'))}</span></td><td>${esc(o.date||'—')}</td></tr>`).join('')||emptyRow(6,'Платежей пока нет')}
function renderAnalytics(){const a=orders(),done=a.filter(o=>o.status==='Завершена');if($('#serviceRevenue')){const rows=services.map(s=>({name:s.name,val:done.filter(o=>o.service===s.name).reduce((x,o)=>x+Number(o.amount||0),0)})).sort((x,y)=>y.val-x.val),max=Math.max(...rows.map(x=>x.val),1);$('#serviceRevenue').innerHTML=rows.map(r=>`<div><span>${esc(r.name)}</span><b>${money(r.val)}</b><i><em style="width:${r.val/max*100}%"></em></i></div>`).join('')}
if($('#carRanking')){const rows=cars.map(c=>({name:c.name,val:a.filter(o=>o.carId===c.id||o.carName===c.name).length})).sort((x,y)=>y.val-x.val),max=Math.max(...rows.map(x=>x.val),1);$('#carRanking').innerHTML=rows.map(r=>`<div><span>${esc(r.name)}</span><b>${r.val} заказов</b><i><em style="width:${r.val/max*100}%"></em></i></div>`).join('')}
if($('#conversionBox')){const total=a.length,confirmed=a.filter(o=>['Подтверждена','Завершена'].includes(o.status)).length,complete=done.length;$('#conversionBox').innerHTML=`<div><b>${total}</b><span>Все заявки</span></div><i>→</i><div><b>${confirmed}</b><span>Подтверждены</span></div><i>→</i><div><b>${complete}</b><span>Завершены</span></div><strong>${total?Math.round(complete/total*100):0}% конверсия</strong>`}}
function renderNotices(){if(!$('#noticeGrid'))return;$('#noticeGrid').innerHTML=notices.map((n,i)=>`<article class="serviceEdit"><div class="serviceTop"><span>MSG</span><label class="switch"><input type="checkbox" ${n.active?'checked':''} onchange="notices[${i}].active=this.checked;persistV3()"><i></i></label></div><input class="serviceName" value="${esc(n.name)}" onchange="notices[${i}].name=this.value;persistV3()"><textarea rows="4" onchange="notices[${i}].text=this.value;persistV3()">${esc(n.text)}</textarea><button class="dangerTxt" onclick="notices.splice(${i},1);persistV3()">Удалить шаблон</button></article>`).join('')}
$('#addNoticeBtn')?.addEventListener('click',()=>{notices.push({id:'n'+Date.now(),name:'Новый шаблон',text:'Текст сообщения клиенту',active:true});persistV3()});
function renderStaff(){if(!$('#staffGrid'))return;$('#staffGrid').innerHTML=staff.map((u,i)=>`<article class="driverCard staffCard"><div class="driverAvatar">${esc(u.name[0])}</div><div class="driverMain"><div class="driverHead"><div><h3>${esc(u.name)}</h3><p>${esc(u.role)}</p></div><span class="driverStatus ${u.active?'free':'busy'}">${u.active?'Активен':'Отключён'}</span></div><div class="driverMeta"><span>${esc(u.phone)}</span><span>${esc(u.access)}</span></div><div class="carActions"><button onclick="staff[${i}].active=!staff[${i}].active;persistV3()">${u.active?'Отключить':'Включить'}</button>${u.role!=='Владелец'?`<button class="dangerTxt" onclick="staff.splice(${i},1);persistV3()">Удалить</button>`:''}</div></div></article>`).join('');if($('#activityLog')){$('#activityLog').innerHTML=[['Система','CRM открыта и данные синхронизированы','только что'],['Администратор','Изменены настройки автопарка','сегодня'],['Диспетчер','Обработана заявка клиента','сегодня']].map(x=>`<article><span class="activityDot"></span><div><b>${x[0]}</b><p>${x[1]}</p></div><small>${x[2]}</small></article>`).join('')}}
$('#addStaffBtn')?.addEventListener('click',()=>{const name=prompt('Имя сотрудника');if(!name)return;const role=prompt('Роль','Менеджер')||'Менеджер';staff.push({id:'u'+Date.now(),name,role,phone:'—',access:'Заказы, клиенты',active:true});persistV3()});
$('#exportOrders')?.addEventListener('click',()=>{const a=orders();const rows=[['ID','Клиент','Телефон','Услуга','Авто','Дата','Время','Сумма','Статус'],...a.map(o=>[o.id,o.name,o.phone,o.service,o.carName,o.date,o.time,o.amount,o.status])];const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),ael=document.createElement('a');ael.href=url;ael.download='qazaq-boss-orders.csv';ael.click();URL.revokeObjectURL(url)});
function renderV3(){renderDrivers();renderPayments();renderAnalytics();renderNotices();renderStaff();const sel=$('#oDriver');if(sel)sel.innerHTML='<option value="">Не назначен</option>'+drivers.map(d=>`<option value="${d.id}">${esc(d.name)} — ${esc(d.status)}</option>`).join('')}
renderAll();


// ===== PRO V6: finance, maintenance, fines, tariffs, promos, driver map =====
let expenses=JSON.parse(localStorage.getItem('qb_expenses')||'null')||[];
let maintenance=JSON.parse(localStorage.getItem('qb_maintenance')||'null')||[];
let fines=JSON.parse(localStorage.getItem('qb_fines')||'null')||[];
let promos=JSON.parse(localStorage.getItem('qb_promos')||'null')||[{id:'p1',code:'BOSS10',type:'percent',value:10,active:true,uses:0,limit:100,expires:'2026-12-31'}];
let tariffs=JSON.parse(localStorage.getItem('qb_tariffs')||'null')||[{id:'t1',name:'Такси — город',base:1500,perKm:250,perMin:35,minFare:2500,active:true},{id:'t2',name:'Трезвый водитель',base:5000,perKm:300,perMin:0,minFare:7000,active:true}];
let driverLocations=JSON.parse(localStorage.getItem('qb_driver_locations')||'null')||[];
function persistV6(key,val){localStorage.setItem(key,JSON.stringify(val));renderV6()}
function renderFinance(){const a=orders(),revenue=a.filter(o=>o.status==='Завершена').reduce((s,o)=>s+Number(o.amount||0),0),exp=expenses.reduce((s,e)=>s+Number(e.amount||0),0),dep=a.filter(o=>!['Завершена','Отменена'].includes(o.status)).reduce((s,o)=>s+Number(o.deposit||0),0);if($('#finRevenue'))$('#finRevenue').textContent=money(revenue);if($('#finExpenses'))$('#finExpenses').textContent=money(exp);if($('#finProfit'))$('#finProfit').textContent=money(revenue-exp);if($('#finDeposits'))$('#finDeposits').textContent=money(dep);if($('#carProfit')){const rows=cars.map(c=>{const rev=a.filter(o=>(o.carId===c.id||o.carName===c.name)&&o.status==='Завершена').reduce((s,o)=>s+Number(o.amount||0),0),cost=expenses.filter(e=>e.carId===c.id).reduce((s,e)=>s+Number(e.amount||0),0);return{name:c.name,val:rev-cost,rev,cost}}).sort((x,y)=>y.val-x.val),max=Math.max(...rows.map(x=>Math.max(x.val,0)),1);$('#carProfit').innerHTML=rows.map(r=>`<div><span>${esc(r.name)}<small>${money(r.rev)} − ${money(r.cost)}</small></span><b>${money(r.val)}</b><i><em style="width:${Math.max(0,r.val)/max*100}%"></em></i></div>`).join('')}if($('#expenseList'))$('#expenseList').innerHTML=expenses.slice().sort((x,y)=>String(y.date).localeCompare(String(x.date))).slice(0,12).map(e=>`<article><div><b>${esc(e.type)}</b><span>${esc(e.carName||'Общие расходы')} • ${esc(e.date||'')}</span></div><strong>${money(e.amount)}</strong><button onclick="deleteExpense('${e.id}')">×</button></article>`).join('')||'<div class="emptyCard">Расходов пока нет</div>'}
window.deleteExpense=id=>{expenses=expenses.filter(x=>x.id!==id);persistV6('qb_expenses',expenses)};
$('#addExpenseBtn')?.addEventListener('click',()=>{const carName=prompt('Автомобиль (можно оставить пустым)','');const car=cars.find(c=>c.name===carName);const type=prompt('Тип расхода','ТО');const amount=Number(prompt('Сумма, ₸','0'));if(!type||!amount)return;expenses.unshift({id:'e'+Date.now(),carId:car?.id||'',carName:car?.name||carName||'',type,amount,date:new Date().toISOString().slice(0,10),comment:''});persistV6('qb_expenses',expenses)});
function renderMaintenance(){if($('#maintenanceList'))$('#maintenanceList').innerHTML=maintenance.slice().sort((a,b)=>String(a.date).localeCompare(String(b.date))).map(m=>`<article><div><b>${esc(m.carName)} — ${esc(m.type)}</b><span>${esc(m.date)} • ${Number(m.mileage||0).toLocaleString('ru-RU')} км • ${esc(m.status)}</span></div><strong>${money(m.cost||0)}</strong><button onclick="toggleMaintenance('${m.id}')">✓</button></article>`).join('')||'<div class="emptyCard">Нет запланированного ТО</div>';if($('#fineList'))$('#fineList').innerHTML=fines.map(f=>`<article><div><b>${esc(f.client||'Клиент')} — ${esc(f.type||'Штраф')}</b><span>#${esc(f.orderId||'—')} • ${esc(f.status||'Новый')}</span></div><strong>${money(f.amount||0)}</strong><button onclick="deleteFine('${f.id}')">×</button></article>`).join('')||'<div class="emptyCard">Штрафов и долгов нет</div>'}
window.toggleMaintenance=id=>{const m=maintenance.find(x=>x.id===id);if(m){m.status=m.status==='Завершено'?'Запланировано':'Завершено';persistV6('qb_maintenance',maintenance)}};window.deleteFine=id=>{fines=fines.filter(x=>x.id!==id);persistV6('qb_fines',fines)};
$('#addMaintenanceBtn')?.addEventListener('click',()=>{const carName=prompt('Автомобиль',cars[0]?.name||'');const car=cars.find(c=>c.name===carName);if(!car)return alert('Выберите автомобиль из автопарка');const type=prompt('Работа','Плановое ТО')||'ТО';const date=prompt('Дата YYYY-MM-DD',new Date().toISOString().slice(0,10));const cost=Number(prompt('Плановая стоимость, ₸','0'));maintenance.push({id:'m'+Date.now(),carId:car.id,carName:car.name,type,date,mileage:0,cost,status:'Запланировано',comment:''});persistV6('qb_maintenance',maintenance)});
$('#addFineBtn')?.addEventListener('click',()=>{const orderId=prompt('ID заказа','');const o=orders().find(x=>String(x.id)===String(orderId));const amount=Number(prompt('Сумма штрафа/долга, ₸','0'));if(!amount)return;fines.unshift({id:'f'+Date.now(),orderId:orderId||'',client:o?.name||prompt('Клиент','')||'',type:prompt('Причина','Штраф')||'Штраф',amount,status:'Новый',payer:'client'});persistV6('qb_fines',fines)});
function renderTariffs(){if($('#tariffList'))$('#tariffList').innerHTML=tariffs.map(t=>`<article><div><b>${esc(t.name)}</b><span>База ${money(t.base)} • ${money(t.perKm)}/км • ${money(t.perMin)}/мин • минимум ${money(t.minFare)}</span></div><strong>${t.active?'Активен':'Выкл.'}</strong><button onclick="toggleTariff('${t.id}')">${t.active?'−':'+'}</button></article>`).join('');if($('#promoList'))$('#promoList').innerHTML=promos.map(p=>`<article><div><b>${esc(p.code)}</b><span>${p.type==='percent'?p.value+'%':money(p.value)} • ${p.uses||0}/${p.limit||'∞'} • до ${esc(p.expires||'—')}</span></div><strong>${p.active?'Активен':'Выкл.'}</strong><button onclick="togglePromo('${p.id}')">${p.active?'−':'+'}</button></article>`).join('')}
window.toggleTariff=id=>{const t=tariffs.find(x=>x.id===id);if(t)t.active=!t.active;persistV6('qb_tariffs',tariffs)};window.togglePromo=id=>{const p=promos.find(x=>x.id===id);if(p)p.active=!p.active;persistV6('qb_promos',promos)};
$('#addTariffBtn')?.addEventListener('click',()=>{const name=prompt('Название тарифа','Такси — новый тариф');if(!name)return;tariffs.push({id:'t'+Date.now(),name,base:Number(prompt('Посадка/база, ₸','1500')),perKm:Number(prompt('За 1 км, ₸','250')),perMin:Number(prompt('За 1 минуту, ₸','35')),minFare:Number(prompt('Минимальная стоимость, ₸','2500')),active:true});persistV6('qb_tariffs',tariffs)});
$('#addPromoBtn')?.addEventListener('click',()=>{const code=(prompt('Промокод','BOSS15')||'').trim().toUpperCase();if(!code)return;promos.push({id:'p'+Date.now(),code,type:'percent',value:Number(prompt('Скидка, %','10')),active:true,uses:0,limit:Number(prompt('Лимит использований','100')),expires:prompt('Действует до YYYY-MM-DD','2026-12-31')});persistV6('qb_promos',promos)});
function renderDriverMap(){if(!$('#driverMap')||!$('#driverMapLegend'))return;const minLat=47.05,maxLat=47.13,minLng=51.86,maxLng=51.98;$('#driverMap').querySelectorAll('.driverPin').forEach(x=>x.remove());driverLocations.forEach(loc=>{const d=drivers.find(x=>x.id===loc.driverId);if(!d)return;const x=Math.max(3,Math.min(97,(Number(loc.lng)-minLng)/(maxLng-minLng)*100)),y=100-Math.max(4,Math.min(96,(Number(loc.lat)-minLat)/(maxLat-minLat)*100));const pin=document.createElement('button');pin.className='driverPin '+(d.status==='Свободен'?'free':'busy');pin.style.left=x+'%';pin.style.top=y+'%';pin.innerHTML=`<b>${esc(d.name[0])}</b><span>${esc(d.name)}<small>${esc(d.status)}</small></span>`;$('#driverMap').appendChild(pin)});$('#driverMapLegend').innerHTML=drivers.map(d=>{const l=driverLocations.find(x=>x.driverId===d.id);return`<article><i class="${d.status==='Свободен'?'free':'busy'}"></i><div><b>${esc(d.name)}</b><span>${esc(d.status)} • ${esc(l?.updated||'нет координат')}</span></div></article>`}).join('')}
function renderV6(){renderFinance();renderMaintenance();renderTariffs();renderDriverMap();const staffSel=$('#oStaff');if(staffSel)staffSel.innerHTML='<option value="">Не назначен</option>'+staff.filter(u=>u.active).map(u=>`<option value="${u.id}">${esc(u.name)} — ${esc(u.role)}</option>`).join('')}
renderV6();


// ===== V16: support/socials/FAQ editor =====
function renderFaqAdmin(){const host=$('#faqAdminList');if(!host)return;settings.faq=Array.isArray(settings.faq)?settings.faq:[];host.innerHTML=settings.faq.map((x,i)=>`<div class="adminCard" style="padding:14px;margin:10px 0;background:#111318"><div style="display:grid;grid-template-columns:1fr auto;gap:10px;align-items:start"><div><label>Вопрос<input data-faq-q="${i}" value="${esc(x.q||'')}"></label><label>Ответ<textarea rows="3" data-faq-a="${i}">${esc(x.a||'')}</textarea></label></div><button class="moreBtn" type="button" onclick="removeFaq(${i})">Удалить</button></div></div>`).join('')||'<div class="emptyCard">FAQ пока пуст. Добавьте первый вопрос.</div>';host.querySelectorAll('[data-faq-q]').forEach(el=>el.oninput=()=>{settings.faq[+el.dataset.faqQ].q=el.value;localStorage.setItem('qb_settings',JSON.stringify(settings))});host.querySelectorAll('[data-faq-a]').forEach(el=>el.oninput=()=>{settings.faq[+el.dataset.faqA].a=el.value;localStorage.setItem('qb_settings',JSON.stringify(settings))})}
window.removeFaq=i=>{settings.faq.splice(i,1);localStorage.setItem('qb_settings',JSON.stringify(settings));renderFaqAdmin()};
$('#addFaqBtn')?.addEventListener('click',()=>{settings.faq=settings.faq||[];settings.faq.push({q:'Новый вопрос',a:'Введите ответ'});localStorage.setItem('qb_settings',JSON.stringify(settings));renderFaqAdmin()});
