(()=>{const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const toast=t=>{const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window._t);window._t=setTimeout(()=>e.classList.remove('show'),2200)};const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');io.unobserve(e.target)}}),{threshold:.08});$$('.reveal').forEach(x=>io.observe(x));
const phraseKz={
'Главная':'Басты бет','Автопарк':'Автопарк','Услуги':'Қызметтер','О нас':'Біз туралы','Отзывы':'Пікірлер','Контакты':'Байланыс','Войти':'Кіру','Главная':'Басты бет','Авто':'Көлік','Поиск':'Іздеу','Избранное':'Таңдаулы','Профиль':'Профиль',
'Премиальный прокат авто в Атырау':'Атырауда премиум автокөлік жалдау','Премиальный':'Премиум','прокат авто':'автокөлік жалдау','в Атырау':'Атырауда',
'Автомобили с водителем и без, такси и услуга «трезвый водитель». Онлайн-бронирование, прозрачные условия и поддержка 24/7.':'Жүргізушімен және жүргізушісіз автокөлік, такси және «трезвый водитель» қызметі. Онлайн брондау, ашық шарттар және 24/7 қолдау.',
'Выбрать автомобиль':'Көлік таңдау','Все услуги':'Барлық қызметтер','Город':'Қала','Получение':'Алу күні','Возврат':'Қайтару','Найти авто':'Көлік табу',
'Премиальный автопарк':'Премиум автопарк','Прозрачные условия':'Ашық шарттар','Поддержка 24/7':'24/7 қолдау','С водителем и без':'Жүргізушімен және жүргізушісіз',
'Актуальные предложения':'Өзекті ұсыныстар','Автомобили QAZAQ BOSS':'QAZAQ BOSS автокөліктері','Смотреть весь автопарк':'Барлық автопаркті көру','Не только аренда':'Тек жалға беру емес','Единая экосистема':'Біртұтас жүйе',
'Автопрокат':'Автокөлік жалдау','Такси':'Такси','Трезвый водитель':'Трезвый водитель','Оформить заявку':'Өтінім қалдыру','Выбрать авто':'Көлік таңдау','Заказать такси':'Такси шақыру','Вызвать водителя':'Жүргізуші шақыру',
'Автопарк':'Автопарк','Поиск по марке или модели':'Марка немесе модель бойынша іздеу','Рекомендуемые':'Ұсынылған','Цена: сначала ниже':'Бағасы: төменнен жоғары','Цена: сначала выше':'Бағасы: жоғарыдан төмен','Любая цена':'Кез келген баға','Все':'Барлығы',
'Все услуги в одном месте':'Барлық қызмет бір жерде','Сервисы QAZAQ BOSS':'QAZAQ BOSS қызметтері','Перейти в автопарк':'Автопаркке өту','Как это работает':'Қалай жұмыс істейді','Просто для клиента. Управляемо для бизнеса.':'Клиентке оңай. Бизнеске ыңғайлы.',
'О компании':'Компания туралы','QAZAQ BOSS AUTORENT':'QAZAQ BOSS AUTORENT','Премиальная мобильность':'Премиум мобильділік','Сервис, где транспорт подбирают под задачу':'Мақсатқа сай көлік таңдайтын сервис','Основной город работы.':'Негізгі жұмыс қаласы.','Заявка доступна в любое время.':'Өтінімді кез келген уақытта қалдыруға болады.','Основной публичный контакт компании.':'Компанияның негізгі ашық байланыс нөмірі.',
'Репутация':'Бедел','Отзывы клиентов':'Клиент пікірлері','Здесь появится отзыв клиента':'Мұнда клиент пікірі пайда болады','Фото и имя — по желанию':'Фото мен аты — қалауы бойынша','Без выдуманных оценок':'Ойдан шығарылған бағасыз','Демо-режим':'Демо режим',
'Связаться':'Байланысу','Телефон':'Телефон','Написать менеджеру':'Менеджерге жазу','Бронирование':'Брондау','Оформить заявку':'Өтінім рәсімдеу','Быстрое оформление':'Жылдам рәсімдеу','Несколько шагов до подтверждения':'Растауға дейін бірнеше қадам','Выберите услугу':'Қызметті таңдаңыз','Оставьте контакты':'Байланыс деректерін қалдырыңыз','Получите подтверждение':'Растауды алыңыз','Имя':'Аты','Дата':'Күні','Время':'Уақыты','Комментарий':'Пікір','Отправить заявку':'Өтінім жіберу','Менеджер подтвердит стоимость и доступность.':'Менеджер баға мен қолжетімділікті растайды.',
'Войти в аккаунт':'Аккаунтқа кіру','Создать аккаунт':'Аккаунт ашу','Управляйте бронированиями, избранными автомобилями и данными профиля.':'Брондауларды, таңдаулы көліктерді және профиль деректерін басқарыңыз.','Регистрация занимает меньше минуты.':'Тіркелу бір минуттан аз уақыт алады.','Ваш аккаунт нужен для быстрого повторного бронирования и сохранения истории поездок.':'Аккаунт қайта брондау және сапар тарихын сақтау үшін қажет.','Телефон или e-mail':'Телефон немесе e-mail','Пароль':'Құпиясөз','Ваш пароль':'Құпиясөзіңіз','Нет аккаунта?':'Аккаунтыңыз жоқ па?','Зарегистрироваться':'Тіркелу','Уже есть аккаунт?':'Аккаунтыңыз бар ма?','Имя':'Аты','Телефон':'Телефон','Повторите пароль':'Құпиясөзді қайталаңыз','Создать аккаунт':'Аккаунт ашу','Обзор':'Шолу','Бронирования':'Брондаулар','Избранное':'Таңдаулы','Новая бронь':'Жаңа бронь','Выйти':'Шығу','Личный кабинет':'Жеке кабинет','Все поездки и данные в одном месте.':'Барлық сапарлар мен деректер бір жерде.','Выбрать авто':'Көлік таңдау','бронирований':'брондау','в избранном':'таңдаулыда','поддержка':'қолдау','Последние бронирования':'Соңғы брондаулар','Статусы обновляются после обработки менеджером.':'Менеджер өңдегеннен кейін мәртебе жаңартылады.','Мои бронирования':'Менің брондауларым','История заявок и текущие статусы.':'Өтінімдер тарихы және ағымдағы мәртебелер.','Избранные автомобили':'Таңдаулы көліктер','Сохранённые варианты для быстрого бронирования.':'Жылдам брондау үшін сақталған нұсқалар.','Автопарк':'Автопарк','Профиль':'Профиль','Контактные данные для более быстрого оформления.':'Жылдам рәсімдеу үшін байланыс деректері.','Город':'Қала','Комментарий к профилю':'Профильге түсініктеме','Сохранить изменения':'Өзгерістерді сақтау','Новое бронирование':'Жаңа брондау','Выберите услугу и отправьте заявку менеджеру.':'Қызметті таңдап, менеджерге өтінім жіберіңіз.','Услуга':'Қызмет','Автомобиль':'Көлік','Выберите автомобиль':'Көлікті таңдаңыз','Адрес подачи':'Беру мекенжайы','Куда':'Қайда','Адрес назначения':'Бару мекенжайы','Дополнительные пожелания':'Қосымша тілектер','Отправить заявку':'Өтінім жіберу','Вернуться в автопарк':'Автопаркке оралу','Добавить в избранное':'Таңдаулыға қосу','Уточнить в WhatsApp':'WhatsApp-та нақтылау','Коробка':'Беріліс қорабы','Автомат':'Автомат','Формат':'Формат','С водителем / без':'Жүргізушімен / жүргізушісіз','сутки':'тәулік'
};
const textNodes=[];function collectText(){const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode()){if(n.parentElement&& !['SCRIPT','STYLE'].includes(n.parentElement.tagName)&&n.nodeValue.trim())textNodes.push([n,n.nodeValue])}}collectText();function translateBody(l){textNodes.forEach(([n,orig])=>{if(l==='ru'){n.nodeValue=orig;return}const lead=orig.match(/^\s*/)?.[0]||'',trail=orig.match(/\s*$/)?.[0]||'',core=orig.trim();if(phraseKz[core])n.nodeValue=lead+phraseKz[core]+trail});}

let lang=localStorage.getItem('qb_lang')||'ru';const dict={ru:{home:'Главная',fleet:'Автопарк',services:'Услуги',about:'О нас',reviews:'Отзывы',contacts:'Контакты',login:'Войти'},kz:{home:'Басты бет',fleet:'Автопарк',services:'Қызметтер',about:'Біз туралы',reviews:'Пікірлер',contacts:'Байланыс',login:'Кіру'}};function setLang(l){lang=l;localStorage.setItem('qb_lang',l);document.documentElement.lang=l;translateBody(l);$$('[data-i18n]').forEach(e=>{const k=e.dataset.i18n;if(dict[l][k])e.textContent=dict[l][k]});const b=$('#langToggle');if(b)b.textContent=l==='ru'?'KZ':'RU'}setLang(lang);$('#langToggle')?.addEventListener('click',()=>setLang(lang==='ru'?'kz':'ru'));
const favs=new Set(JSON.parse(localStorage.getItem('qb_favorites_lux')||'[]'));function paintFav(){$$('[data-fav]').forEach(b=>b.classList.toggle('on',favs.has(b.dataset.fav)))}paintFav();document.addEventListener('click',e=>{const b=e.target.closest('[data-fav]');if(!b)return;const id=b.dataset.fav;favs.has(id)?favs.delete(id):favs.add(id);localStorage.setItem('qb_favorites_lux',JSON.stringify([...favs]));paintFav();toast(favs.has(id)?'Добавлено в избранное':'Удалено из избранного')});
const q=$('#fleetSearch'),sort=$('#fleetSort'),price=$('#fleetPrice');let cat='all';function filter(){const cards=$$('#fleetGrid .car-card');let visible=0;cards.forEach(c=>{const okQ=!q?.value||c.dataset.name.includes(q.value.toLowerCase());const okC=cat==='all'||c.dataset.cat.includes(cat);const okP=+c.dataset.price<=+(price?.value||999999);const ok=okQ&&okC&&okP;c.style.display=ok?'':'none';if(ok)visible++});if(sort){const grid=$('#fleetGrid');cards.sort((a,b)=>sort.value==='asc'?+a.dataset.price-+b.dataset.price:sort.value==='desc'?+b.dataset.price-+a.dataset.price:0).forEach(c=>grid.appendChild(c))}if($('#fleetEmpty'))$('#fleetEmpty').style.display=visible?'none':'block'}q?.addEventListener('input',filter);sort?.addEventListener('change',filter);price?.addEventListener('change',filter);$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-filter]').forEach(x=>x.classList.remove('on'));b.classList.add('on');cat=b.dataset.filter;filter()}));
$('#heroBooking')?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);location.href=`fleet.html?start=${encodeURIComponent(fd.get('start')||'')}&end=${encodeURIComponent(fd.get('end')||'')}`});
const bs=$('#bookingService'),cf=$('#carField');function serviceUI(){if(!bs||!cf)return;cf.style.display=(bs.value==='Автопрокат'||bs.value==='Аренда с водителем')?'grid':'none'}bs?.addEventListener('change',serviceUI);serviceUI();const ps=new URLSearchParams(location.search);if(bs&&ps.get('service')){bs.value=ps.get('service')==='taxi'?'Такси':ps.get('service')==='sober'?'Трезвый водитель':bs.value;serviceUI()}if($('#bookingCar')&&ps.get('car'))$('#bookingCar').value=ps.get('car');
$('#mainBooking')?.addEventListener('submit',async e=>{e.preventDefault();const s=$('#bookingStatus');const carSel=$('#bookingCar'),carText=carSel?.selectedOptions?.[0]?.textContent||'';const priceMatch=carText.match(/([\d\s]+) ₸/);const order={id:Date.now(),service:bs.value,name:$('#bookingName').value.trim(),phone:$('#bookingPhone').value.trim(),date:$('#bookingDate').value,time:$('#bookingTime').value,comment:$('#bookingComment').value.trim(),status:'Новая',amount:priceMatch?Number(priceMatch[1].replace(/\s/g,'')):0,carId:carSel?.value||'',carName:carSel?.value?carText.split(' — ')[0]:'',created:new Date().toLocaleString('ru-RU')};if(order.phone.replace(/\D/g,'').length<10){s.textContent='Проверьте номер телефона.';s.style.color='#df6e6e';return}s.textContent='Отправляем заявку…';try{if(location.protocol.startsWith('http')){const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(order)});if(!r.ok)throw new Error()}else{const a=JSON.parse(localStorage.getItem('qb_orders')||'[]');a.unshift(order);localStorage.setItem('qb_orders',JSON.stringify(a))}s.textContent='Заявка принята. Менеджер свяжется с вами для подтверждения.';s.style.color='#50b987';toast('Заявка отправлена')}catch{const a=JSON.parse(localStorage.getItem('qb_orders')||'[]');a.unshift(order);localStorage.setItem('qb_orders',JSON.stringify(a));s.textContent='Заявка сохранена на устройстве. Для синхронизации запустите сайт через сервер.';s.style.color='#dcb25d'}});
const dt=$$('#bookingDate,[name=start],[name=end]');const now=new Date();now.setMinutes(now.getMinutes()-now.getTimezoneOffset());dt.forEach(x=>x.min=now.toISOString().slice(0,10));})();