
(function(){
const D=document, qs=s=>D.querySelector(s), qsa=s=>[...D.querySelectorAll(s)];
const defaults={company:'QAZAQ BOSS AUTORENT',whatsapp:'77752757063',phone:'+7 775 275 70 63',city:'Атырау',hours:'24/7 — онлайн-заявки',instagram:'',twoGis:'',supportEmail:'',faq:[
{q:'Какие документы нужны для аренды?',a:'Обычно нужны удостоверение личности и водительское удостоверение. Точные условия менеджер подтверждает перед бронированием.'},
{q:'Можно забронировать автомобиль с телефона?',a:'Да. Выберите автомобиль, даты и отправьте заявку. После подтверждения бронь появится в личном кабинете.'},
{q:'Можно заказать автомобиль с водителем?',a:'Да. Доступны аренда с водителем, такси и услуга трезвого водителя.'},
{q:'Как узнать, свободен ли автомобиль?',a:'Статус показывается в каталоге. Финальную доступность на выбранные даты подтверждает менеджер.'},
{q:'Как связаться с поддержкой?',a:'Используйте WhatsApp, телефон, Instagram или другие активные каналы в разделе поддержки.'}
]};
function getSettings(){try{return {...defaults,...JSON.parse(localStorage.getItem('qb_settings')||'{}')}}catch(e){return defaults}}
function icon(n){const p={wa:'<path d="M20.5 3.5A10 10 0 0 0 4.8 15.6L3 21l5.6-1.7A10 10 0 1 0 20.5 3.5Z"/><path d="M8.5 8.2c.4 3 3 5.5 6 6.1.7.1 1.4-.8 1.8-1.4"/>',ig:'<rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/>',gis:'<path d="M12 22s7-6.1 7-13a7 7 0 1 0-14 0c0 6.9 7 13 7 13Z"/><circle cx="12" cy="9" r="2.5"/>',phone:'<path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.4 19.4 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7 12.8 12.8 0 0 0 .7 2.8 2 2 0 0 1-.5 2.1L8 9.9a16 16 0 0 0 6 6l1.3-1.3a2 2 0 0 1 2.1-.5 12.8 12.8 0 0 0 2.8.7A2 2 0 0 1 22 16.9z"/>',msg:'<path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4z"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9.8 9a2.5 2.5 0 1 1 4.2 1.8c-1 .8-2 1.2-2 2.7M12 17h.01"/>',more:'<circle cx="5" cy="12" r="1.5" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r="1.5" fill="currentColor" stroke="none"/><circle cx="19" cy="12" r="1.5" fill="currentColor" stroke="none"/>'};return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">'+(p[n]||p.help)+'</svg>'}
function linkSafe(v){return /^https?:\/\//i.test(v||'')?v:'#'}
function mount(){if(D.body.classList.contains('adminBody'))return;const s=getSettings(),wa='https://wa.me/'+String(s.whatsapp||'').replace(/\D/g,'');
qsa('link[rel="stylesheet"]').length && !qs('link[href="support-v16.css"]') && D.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="support-v16.css">');
const old=D.querySelector('footer'); if(old) old.remove();
D.body.insertAdjacentHTML('beforeend',`<footer class="qb-footer"><div class="wrap"><div class="qb-footer-grid"><div><div class="qb-footer-brand">QAZAQ <em>BOSS</em></div><p>Премиальный автопрокат и услуги водителя. Быстрое бронирование и поддержка ${s.hours||'24/7'}.</p><div class="qb-socials"><a href="${wa}" target="_blank" aria-label="WhatsApp">${icon('wa')}</a>${s.instagram?`<a href="${linkSafe(s.instagram)}" target="_blank" aria-label="Instagram">${icon('ig')}</a>`:''}${s.twoGis?`<a href="${linkSafe(s.twoGis)}" target="_blank" aria-label="2GIS">${icon('gis')}</a>`:''}<a href="tel:${String(s.phone||'').replace(/[^+\d]/g,'')}" aria-label="Телефон">${icon('phone')}</a></div></div><div><h4>Навигация</h4><a href="index.html">Главная</a><a href="fleet.html">Автопарк</a><a href="services.html">Услуги</a><a href="about.html">О компании</a></div><div><h4>Клиентам</h4><a href="support.html#faq">FAQ</a><a href="account.html">Личный кабинет</a><a href="reviews.html">Отзывы</a><a href="contacts.html">Контакты</a></div><div><h4>Поддержка</h4><a href="${wa}" target="_blank">WhatsApp</a>${s.instagram?`<a href="${linkSafe(s.instagram)}" target="_blank">Instagram</a>`:''}${s.twoGis?`<a href="${linkSafe(s.twoGis)}" target="_blank">2GIS</a>`:''}<a href="tel:${String(s.phone||'').replace(/[^+\d]/g,'')}">${s.phone}</a><a href="support.html">Центр поддержки</a></div></div><div class="qb-footer-bottom"><span>© ${new Date().getFullYear()} QAZAQ BOSS AUTORENT</span><span>${s.city} • ${s.hours}</span></div></div></footer>`);
D.body.insertAdjacentHTML('beforeend',`<button class="qb-support-fab" id="qbSupportFab" aria-label="Поддержка">${icon('msg')}</button><div class="qb-sheet-backdrop" id="qbSheetBackdrop"></div><section class="qb-support-sheet" id="qbSupportSheet"><div class="qb-sheet-head"><div><small style="color:#d6ad5c">QAZAQ BOSS</small><h3>Поддержка</h3></div><button class="qb-sheet-close" id="qbSheetClose">×</button></div><div class="qb-sheet-actions"><a href="${wa}" target="_blank"><b>${icon('wa')} WhatsApp</b><span>Написать менеджеру</span></a>${s.instagram?`<a href="${linkSafe(s.instagram)}" target="_blank"><b>${icon('ig')} Instagram</b><span>Открыть профиль</span></a>`:''}${s.twoGis?`<a href="${linkSafe(s.twoGis)}" target="_blank"><b>${icon('gis')} 2GIS</b><span>Открыть карточку и маршрут</span></a>`:''}<a href="tel:${String(s.phone||'').replace(/[^+\d]/g,'')}"><b>${icon('phone')} Позвонить</b><span>${s.phone}</span></a></div><div class="qb-sheet-faq"><a href="support.html#faq"><span><b>FAQ и помощь</b><br><small>Ответы на частые вопросы</small></span><b>→</b></a></div></section>`);
const nav=qs('.mobile-nav'); if(nav){const links=[...nav.querySelectorAll('a')];const search=links.find(a=>(a.textContent||'').trim().toLowerCase().includes('поиск')); if(search) search.dataset.v16HideMobile='1'; if(!nav.querySelector('.qb-mobile-more'))nav.insertAdjacentHTML('beforeend',`<a href="#" class="qb-mobile-more" id="qbMobileMore">${icon('more')}<span>Ещё</span></a>`)}
const sh=qs('#qbSupportSheet'),bd=qs('#qbSheetBackdrop');const open=()=>{sh?.classList.add('open');bd?.classList.add('open');D.body.style.overflow='hidden'},close=()=>{sh?.classList.remove('open');bd?.classList.remove('open');D.body.style.overflow=''};qs('#qbSupportFab')?.addEventListener('click',open);qs('#qbMobileMore')?.addEventListener('click',e=>{e.preventDefault();open()});qs('#qbSheetClose')?.addEventListener('click',close);bd?.addEventListener('click',close);
qsa('.faq-q').forEach(b=>b.addEventListener('click',()=>b.closest('.faq-item').classList.toggle('open')))
}
if(D.readyState==='loading')D.addEventListener('DOMContentLoaded',mount);else mount();
})();
