// QAZAQ BOSS AUTORENT — PRO V7 operations layer
const v7Store=(k,d=[])=>JSON.parse(localStorage.getItem(k)||'null')||d;
let inspections=v7Store('qb_inspections',[]), vehicleHistory=v7Store('qb_vehicle_history',[]);
const v7save=(k,v)=>{localStorage.setItem(k,JSON.stringify(v)); try{window.qbPushState?.(k,v)}catch(e){}};
function openOrderDetails(id){const o=orders().find(x=>String(x.id)===String(id));if(!o)return;const d=drivers.find(x=>x.id===o.driverId),c=cars.find(x=>x.id===o.carId);$('#orderDetailsBody').innerHTML=`
<div class="detailHero"><div><span class="statusPill ${statusClass(o.status)}">${esc(o.status)}</span><h2>#${String(o.id).slice(-6)} · ${esc(o.name||'Клиент')}</h2><p>${esc(o.service||'')} ${o.carName?'• '+esc(o.carName):''}</p></div><b>${money(o.amount||0)}</b></div>
<div class="detailGrid"><article><small>Клиент</small><b>${esc(o.name||'—')}</b><span>${esc(o.phone||'—')}</span></article><article><small>Дата / время</small><b>${esc(o.date||'—')}</b><span>${esc(o.time||'Не указано')}</span></article><article><small>Автомобиль</small><b>${esc(c?.name||o.carName||'Не назначен')}</b><span>${esc(c?.plate||'')}</span></article><article><small>Водитель</small><b>${esc(d?.name||o.driverName||'Не назначен')}</b><span>${esc(d?.phone||'')}</span></article><article><small>Оплата</small><b>${esc(o.paymentStatus||'Ожидается')}</b><span>${esc(o.paymentMethod||'')}</span></article><article><small>Депозит / долг</small><b>${money(o.deposit||0)}</b><span>Долг: ${money(o.debt||0)}</span></article></div>
<div class="detailActions"><a class="btn secondary" href="tel:${esc(o.phone||'')}">Позвонить</a><a class="btn secondary" target="_blank" href="https://wa.me/${String(o.phone||'').replace(/\D/g,'')}">WhatsApp</a><button class="btn primary" onclick="closeModal('orderDetailsModal');editOrder(${JSON.stringify(o.id)})">Редактировать</button></div>
<div class="timeline"><h3>История заказа</h3>${['Новая','В работе','Подтверждена','Завершена'].map((s,i)=>`<div class="timelineRow ${['Новая','В работе','Подтверждена','Завершена'].indexOf(o.status)>=i?'done':''}"><i></i><div><b>${s}</b><span>${i===0?esc(o.created||'Создан'):''}</span></div></div>`).join('')}</div>`;
$('#orderDetailsModal').classList.add('open')}
window.openOrderDetails=openOrderDetails;
const oldRowHtml=rowHtml; rowHtml=function(o,compact=false){const html=oldRowHtml(o,compact);return compact?html:html.replace(`<button class="moreBtn" onclick="editOrder(${o.id})">Изм.</button>`,`<button class="moreBtn" onclick="openOrderDetails(${JSON.stringify(o.id)})">Открыть</button>`)};

function renderDispatch(){if(!$('#dispatchBoard'))return;const active=orders().filter(o=>!['Завершена','Отменена'].includes(o.status));const cols=['Новая','В работе','Подтверждена'];$('#dispatchBoard').innerHTML=cols.map(s=>`<section class="dispatchCol"><header><b>${s}</b><em>${active.filter(o=>o.status===s).length}</em></header><div>${active.filter(o=>o.status===s).map(o=>`<article class="dispatchOrder" onclick="openOrderDetails(${JSON.stringify(o.id)})"><div><span>${esc(o.service)}</span><b>#${String(o.id).slice(-6)}</b></div><h4>${esc(o.name||'Клиент')}</h4><p>${esc(o.from||o.extra?.from||o.carName||'Адрес/авто не указан')}</p><footer><small>${esc(o.time||'Без времени')}</small><strong>${money(o.amount||0)}</strong></footer></article>`).join('')||'<div class="emptyCard">Нет заказов</div>'}</div></section>`).join('');
const free=drivers.filter(d=>d.status==='Свободен').length;$('#dispatchFree').textContent=free;$('#dispatchActive').textContent=active.length;$('#dispatchUnassigned').textContent=active.filter(o=>!o.driverId).length}

function renderInspection(){if(!$('#inspectionList'))return;$('#inspectionList').innerHTML=inspections.slice().reverse().map(x=>`<article class="inspectionCard"><div><span class="statusPill ${x.type==='Выдача'?'ok':'work'}">${esc(x.type)}</span><h3>${esc(x.carName)}</h3><p>${esc(x.client)} • #${esc(x.orderId)}</p></div><div class="inspectionMeta"><span>Пробег <b>${Number(x.mileage||0).toLocaleString('ru-RU')} км</b></span><span>Топливо <b>${esc(x.fuel||'—')}</b></span><span>Повреждения <b>${x.damage?'Есть':'Нет'}</b></span></div><small>${esc(x.created)}</small></article>`).join('')||'<div class="emptyCard">Актов выдачи и возврата пока нет</div>'}
function addInspection(type){const a=orders().filter(o=>o.carName);if(!a.length)return alert('Сначала нужен заказ с автомобилем');const id=prompt('ID заказа',String(a[0].id));const o=a.find(x=>String(x.id)===String(id));if(!o)return alert('Заказ не найден');const mileage=Number(prompt('Пробег, км','0'));const fuel=prompt('Уровень топлива','Полный бак')||'';const damage=confirm('Есть новые повреждения?');const note=damage?(prompt('Опишите повреждения','')||'Повреждение отмечено'):'';const row={id:'i'+Date.now(),type,orderId:o.id,client:o.name,carId:o.carId,carName:o.carName,mileage,fuel,damage,note,created:new Date().toLocaleString('ru-RU')};inspections.push(row);vehicleHistory.push({id:'h'+Date.now(),carId:o.carId,carName:o.carName,type:'Акт: '+type,detail:`${mileage} км • ${fuel}${note?' • '+note:''}`,date:new Date().toISOString().slice(0,10)});v7save('qb_inspections',inspections);v7save('qb_vehicle_history',vehicleHistory);renderV7()}
$('#issueActBtn')?.addEventListener('click',()=>addInspection('Выдача'));$('#returnActBtn')?.addEventListener('click',()=>addInspection('Возврат'));

function renderVehicleHistory(){if(!$('#vehicleHistory'))return;const rows=[...vehicleHistory,...maintenance.map(m=>({carId:m.carId,carName:m.carName,type:'ТО: '+m.type,detail:`${m.status} • ${money(m.cost||0)}`,date:m.date})),...expenses.filter(e=>e.carId).map(e=>({carId:e.carId,carName:e.carName,type:'Расход: '+e.type,detail:money(e.amount),date:e.date}))].sort((a,b)=>String(b.date).localeCompare(String(a.date)));$('#vehicleHistory').innerHTML=rows.map(r=>`<article><div><b>${esc(r.carName||'Автомобиль')}</b><span>${esc(r.type)}</span></div><p>${esc(r.detail||'')}</p><small>${esc(r.date||'')}</small></article>`).join('')||'<div class="emptyCard">История появится после ТО, расходов и актов.</div>'}

function renderRolePreview(){if(!$('#roleMatrix'))return;const roles=[['Владелец','Все разделы, финансы, настройки, сотрудники'],['Менеджер','Заказы, клиенты, оплаты, автопарк'],['Диспетчер','Заказы такси, водители, карта, статусы'],['Водитель','Только назначенные заказы, статус, геопозиция']];$('#roleMatrix').innerHTML=roles.map(r=>`<article><b>${r[0]}</b><span>${r[1]}</span></article>`).join('')}
function renderV7(){renderDispatch();renderInspection();renderVehicleHistory();renderRolePreview()}
const baseRenderAll=renderAll;renderAll=function(){baseRenderAll();renderV7()};
renderV7();
