(()=>{
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('ru-RU').format(Math.round(Number(n)||0))+' ₸';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const daysBetween=(a,b)=>{if(!a)return 1;const x=new Date(a+'T12:00:00'),y=new Date((b||a)+'T12:00:00');return Math.max(1,Math.round((y-x)/86400000)+1)};
function getCars(){try{return JSON.parse(localStorage.getItem('qb_cars')||'[]')}catch{return []}}
function qsCar(id){return getCars().find(c=>String(c.id)===String(id))}

// Premium search overlay
const hero=$('.hero');
if(hero){hero.style.position='relative';hero.insertAdjacentHTML('beforeend',`<div class="premiumSearch"><div class="premiumSearchGrid"><label><small>Услуга</small><select id="v8HeroService"><option>Автопрокат</option><option>Такси</option><option>Трезвый водитель</option><option>Аренда с водителем</option></select></label><label><small>Начало</small><input id="v8HeroStart" type="date"></label><label><small>Возврат</small><input id="v8HeroEnd" type="date"></label><label><small>Время</small><input id="v8HeroTime" type="time"></label><button class="btn primary" id="v8HeroGo">Найти автомобиль</button></div></div>`)}
const quick=$('#quick');if(quick) quick.style.display='none';
hero?.insertAdjacentHTML('afterend',`<div class="trustStrip"><article><i>✓</i><div><b>Проверенные автомобили</b><span>Контроль состояния перед выдачей</span></div></article><article><i>24</i><div><b>Поддержка 24/7</b><span>Связь с менеджером и диспетчером</span></div></article><article><i>₸</i><div><b>Прозрачная стоимость</b><span>Расчёт аренды до подтверждения</span></div></article><article><i>↗</i><div><b>Быстрое оформление</b><span>Бронь с телефона за несколько шагов</span></div></article></div>`);

// VIP section and taxi estimator
const fleet=$('#fleet');
if(fleet) fleet.insertAdjacentHTML('afterend',`<section class="vipSection"><div class="vipCard"><div><span class="eyebrow">QAZAQ BOSS EXPERIENCE</span><h2>Не просто аренда.<br>Ваш транспортный сервис.</h2><p>Аренда автомобиля, машина с водителем, такси и трезвый водитель — в одном интерфейсе, с единым профилем и историей заказов.</p><div class="actions"><button class="btn primary" id="v8OpenWizard">Забронировать</button><a class="btn secondary" href="#services">Все услуги</a></div></div><div class="vipBenefits"><article><b>Онлайн-доступность</b><span>Проверка автомобиля по выбранным датам</span></article><article><b>Единая CRM</b><span>Заказ сразу попадает менеджеру и диспетчеру</span></article><article><b>Контроль аренды</b><span>Депозит, документы, выдача и возврат</span></article><article><b>Личный кабинет</b><span>Заказы, избранное и уведомления клиента</span></article></div></div></section>
<section class="routeEstimator" id="routeEstimate"><div class="routeBox"><div class="routeForm"><span class="eyebrow">ТАКСИ / ТРЕЗВЫЙ ВОДИТЕЛЬ</span><h2>Рассчитайте поездку</h2><div class="routeFields"><label><i>●</i><input id="v8From" placeholder="Откуда забрать"></label><label><i>◆</i><input id="v8To" placeholder="Куда едем"></label></div><div class="routeMeta"><div><span>Расстояние*</span><b id="v8Distance">8.4 км</b></div><div><span>В пути*</span><b id="v8Duration">18 мин</b></div><div><span>Ориентир*</span><b id="v8TaxiPrice">3 200 ₸</b></div></div><button class="btn primary full" style="margin-top:14px" id="v8TaxiOrder">Заказать поездку</button><small style="display:block;margin-top:10px;color:#7f8994">* Демо-расчёт. Для боевого маршрута подключается 2GIS/Google Maps API.</small></div><div class="routeVisual"><span class="routePin a"></span><span class="routePin b"></span></div></div></section>`);

// Modals
const modalHtml=`<div class="modal v8Modal" id="v8CarModal"><div class="modalCard"><div id="v8CarBody"></div></div></div>
<div class="modal v8Modal" id="v8Wizard"><div class="modalCard wizardShell"><div class="wizardTop"><div><small class="eyebrow">ОНЛАЙН-БРОНИРОВАНИЕ</small><h2>Оформление аренды</h2></div><div style="display:flex;align-items:center;gap:18px"><div class="wizardSteps"><i class="on"></i><i></i><i></i><i></i></div><button class="v8Close" data-v8-close>×</button></div></div><div class="wizardBody">
<section class="wizardPane on" data-step="1"><h3>Выберите автомобиль и даты</h3><div class="wizardGrid"><label>Автомобиль<select id="wizCar"></select></label><label>Место получения<select id="wizPlace"><option>Атырау — офис</option><option>Аэропорт Атырау</option><option>Доставка по адресу</option></select></label><label>Дата начала<input id="wizStart" type="date"></label><label>Дата возврата<input id="wizEnd" type="date"></label><label>Время получения<input id="wizTime" type="time" value="10:00"></label><label>Время возврата<input id="wizReturnTime" type="time" value="10:00"></label></div></section>
<section class="wizardPane" data-step="2"><h3>Дополнительные опции</h3><div class="wizardExtras"><label class="extraCard"><input type="checkbox" data-extra="driver" data-price="15000"><b>Личный водитель <span>+15 000 ₸/день</span></b><p>Профессиональный водитель на весь период аренды.</p></label><label class="extraCard"><input type="checkbox" data-extra="insurance" data-price="7000"><b>Расширенная защита <span>+7 000 ₸/день</span></b><p>Демо-пакет дополнительной защиты автомобиля.</p></label><label class="extraCard"><input type="checkbox" data-extra="delivery" data-price="5000"><b>Доставка автомобиля <span>+5 000 ₸</span></b><p>Подача автомобиля по адресу в пределах города.</p></label><label class="extraCard"><input type="checkbox" data-extra="child" data-price="2500"><b>Детское кресло <span>+2 500 ₸</span></b><p>Подготовим и установим кресло перед выдачей.</p></label></div></section>
<section class="wizardPane" data-step="3"><h3>Контактные данные</h3><div class="wizardGrid"><label>Имя<input id="wizName" placeholder="Ваше имя"></label><label>Телефон<input id="wizPhone" placeholder="+7 7__ ___ __ __"></label><label>E-mail<input id="wizEmail" type="email" placeholder="name@example.com"></label><label>Способ оплаты<select id="wizPayment"><option>Kaspi / перевод</option><option>Наличными</option><option>Банковская карта</option></select></label></div><label style="margin-top:14px">Комментарий<input id="wizComment" placeholder="Пожелания к заказу"></label></section>
<section class="wizardPane" data-step="4"><h3>Проверьте заказ</h3><div class="wizardSummary"><div class="summaryRows" id="wizSummaryRows"></div><div class="summaryCard"><small>Итого аренда и опции</small><div class="total"><span>К оплате*</span><strong id="wizTotal">0 ₸</strong></div><div style="margin-top:16px"><small>Возвратный депозит*</small><b id="wizDeposit" style="display:block;margin-top:5px">0 ₸</b></div><small style="display:block;margin-top:14px">* Финальная стоимость и депозит подтверждаются менеджером.</small></div></div></section>
</div><div class="wizardFoot"><button class="btn secondary" id="wizPrev">Назад</button><button class="btn primary" id="wizNext">Продолжить</button></div></div></div>`;
document.body.insertAdjacentHTML('beforeend',modalHtml);
let step=1;
function modal(id,on=true){$(id)?.classList.toggle('open',on);document.body.style.overflow=on?'hidden':''}
function carsForSelect(){const cars=getCars().filter(c=>c.active!==false);$('#wizCar').innerHTML=cars.map(c=>`<option value="${esc(c.id)}">${esc(c.name)} — ${money(c.price)}/сутки</option>`).join('')}
function openWizard(carId){carsForSelect();if(carId)$('#wizCar').value=String(carId);const today=new Date(),tom=new Date(Date.now()+86400000);const fmt=d=>d.toISOString().slice(0,10);$('#wizStart').value=$('#v8HeroStart')?.value||fmt(today);$('#wizEnd').value=$('#v8HeroEnd')?.value||fmt(tom);const p=JSON.parse(localStorage.getItem('qb_profile')||'{}');$('#wizName').value=p.name||'';$('#wizPhone').value=p.phone||'';$('#wizEmail').value=p.email||'';setStep(1);modal('#v8Wizard',true)}
function setStep(n){step=Math.max(1,Math.min(4,n));$$('.wizardPane').forEach(p=>p.classList.toggle('on',Number(p.dataset.step)===step));$$('.wizardSteps i').forEach((i,k)=>i.classList.toggle('on',k<step));$('#wizPrev').style.visibility=step===1?'hidden':'visible';$('#wizNext').textContent=step===4?'Подтвердить заявку':'Продолжить';if(step===4)renderSummary()}
function totals(){const car=qsCar($('#wizCar').value)||{},d=daysBetween($('#wizStart').value,$('#wizEnd').value);let extra=0;$$('[data-extra]:checked').forEach(x=>{const p=Number(x.dataset.price);extra+=['driver','insurance'].includes(x.dataset.extra)?p*d:p});const rent=Number(car.price||0)*d;return{car,d,rent,extra,total:rent+extra,deposit:Math.max(50000,Math.round(rent*.45/10000)*10000)}}
function renderSummary(){const t=totals();$('#wizSummaryRows').innerHTML=`<div><span>Автомобиль</span><b>${esc(t.car.name||'—')}</b></div><div><span>Период</span><b>${t.d} дн.</b></div><div><span>Аренда</span><b>${money(t.rent)}</b></div><div><span>Доп. опции</span><b>${money(t.extra)}</b></div><div><span>Получение</span><b>${esc($('#wizPlace').value)}</b></div><div><span>Оплата</span><b>${esc($('#wizPayment').value)}</b></div>`;$('#wizTotal').textContent=money(t.total);$('#wizDeposit').textContent=money(t.deposit)}
async function submitWizard(){const t=totals();if(!$('#wizName').value.trim()||!$('#wizPhone').value.trim()){setStep(3);return}const order={id:Date.now(),service:'Автопрокат',name:$('#wizName').value.trim(),phone:$('#wizPhone').value.trim(),date:$('#wizStart').value,time:$('#wizTime').value,comment:$('#wizComment').value,status:'Новая',amount:t.total,carId:t.car.id,carName:t.car.name,extra:{endDate:$('#wizEnd').value,pickup:$('#wizPlace').value,payment:$('#wizPayment').value,deposit:t.deposit,extras:$$('[data-extra]:checked').map(x=>x.dataset.extra)},created:new Date().toLocaleString('ru-RU')};try{if(location.protocol.startsWith('http')){const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(order)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Ошибка бронирования')}else{const a=JSON.parse(localStorage.getItem('qb_orders')||'[]');a.unshift(order);localStorage.setItem('qb_orders',JSON.stringify(a))}localStorage.setItem('qb_profile',JSON.stringify({...(JSON.parse(localStorage.getItem('qb_profile')||'{}')),name:order.name,phone:order.phone,email:$('#wizEmail').value}));modal('#v8Wizard',false);window.dispatchEvent(new Event('storage'));alert('Заявка создана. Менеджер QAZAQ BOSS подтвердит автомобиль, стоимость и депозит.')}catch(e){alert(e.message||'Не удалось создать заявку')}}
$('#wizNext').onclick=()=>step<4?setStep(step+1):submitWizard();$('#wizPrev').onclick=()=>setStep(step-1);$$('[data-extra]').forEach(x=>x.onchange=()=>x.closest('.extraCard').classList.toggle('on',x.checked));$$('[data-v8-close]').forEach(x=>x.onclick=()=>modal('#v8Wizard',false));$('#v8Wizard').onclick=e=>{if(e.target.id==='v8Wizard')modal('#v8Wizard',false)};
$('#v8OpenWizard')?.addEventListener('click',()=>openWizard());$('#v8HeroGo')?.addEventListener('click',()=>{const s=$('#v8HeroService').value;if(s==='Автопрокат')openWizard();else{const svc=$('#service');if(svc)svc.value=s;location.hash='booking'}});

function openCar(id){const c=qsCar(id);if(!c)return;$('#v8CarBody').innerHTML=`<div class="v8CarDetail"><div class="v8CarGallery"><img src="${esc(c.image||'assets/car-front.jpg')}" alt="${esc(c.name)}"></div><div class="v8CarInfo"><div><span class="category">${esc((c.category||'PREMIUM').toUpperCase())}</span><h2>${esc(c.name)}</h2><p style="color:#95a0aa">${esc(c.description||'Премиальный автомобиль QAZAQ BOSS AUTORENT для поездок по Атырау и межгороду.')}</p></div><div class="v8SpecGrid"><div><span>Год</span><b>${esc(c.year||'2024')}</b></div><div><span>Коробка</span><b>${esc(c.gear||'Автомат')}</b></div><div><span>Мест</span><b>${esc(c.seats||5)}</b></div><div><span>Статус</span><b>${c.availability==='busy'?'Занят':'Свободен'}</b></div></div><div class="v8PriceBox"><small>Стоимость аренды</small><div><strong>${money(c.price)}</strong> <small>/ сутки</small></div><div class="v8PriceActions"><button class="btn primary" id="detailBook">Выбрать даты</button><button class="btn secondary" data-v8-car-close>Закрыть</button></div></div></div></div>`;modal('#v8CarModal',true);$('#detailBook').onclick=()=>{modal('#v8CarModal',false);openWizard(c.id)};$('[data-v8-car-close]').onclick=()=>modal('#v8CarModal',false)}
$('#v8CarModal').onclick=e=>{if(e.target.id==='v8CarModal')modal('#v8CarModal',false)};
document.addEventListener('click',e=>{const card=e.target.closest('.fleet .car');if(!card||e.target.closest('button,a'))return;const book=card.querySelector('[data-car]');if(book)openCar(book.dataset.car)});

// Taxi demo estimator
function recalcTaxi(){const a=$('#v8From')?.value.trim(),b=$('#v8To')?.value.trim();let km=8.4;if(a||b)km=Math.min(42,Math.max(4,5+(a.length+b.length)*.22));const min=Math.round(km*2.15);const price=Math.max(2500,1200+km*230+min*18);$('#v8Distance').textContent=km.toFixed(1)+' км';$('#v8Duration').textContent=min+' мин';$('#v8TaxiPrice').textContent=money(price)}
$('#v8From')?.addEventListener('input',recalcTaxi);$('#v8To')?.addEventListener('input',recalcTaxi);$('#v8TaxiOrder')?.addEventListener('click',()=>{const s=$('#service');if(s){s.value='Такси';s.dispatchEvent(new Event('change'))}const f=$('#fromAddr'),t=$('#toAddr');if(f)f.value=$('#v8From').value;if(t)t.value=$('#v8To').value;location.hash='booking'});

// Admin subtle production badge
if(document.body.classList.contains('adminBody')){$('.adminTop .topActions')?.insertAdjacentHTML('afterbegin','<span class="v8AdminBadge">● LIVE OPERATIONS</span>')}
})();
